class_path: cmmvae.models.CMMVAEModel
init_args:
  kl_annealing_fn:
    class_path: cmmvae.modules.base.annealing_fn.LinearKLAnnealingFn
    init_args:
      min_kl_weight: 0.1
      max_kl_weight: 2.0
      warmup_steps: 1e3
      climax_steps: 6e3
  record_gradients: false
  adv_weight: 0.25
  cycle_weight: 8.00
  adversarial_method: "GRF"
  gradient_record_cap: 20
  autograd_config:
    class_path: cmmvae.config.AutogradConfig
    init_args:
      adversarial_gradient_clip:
        class_path: cmmvae.config.GradientClipConfig
        init_args:
          val: 10
          algorithm: norm
      vae_gradient_clip:
        class_path: cmmvae.config.GradientClipConfig
        init_args:
          val: 10
          algorithm: norm
      expert_gradient_clip:
        class_path: cmmvae.config.GradientClipConfig
        init_args:
          val: 10
          algorithm: norm
  module:
    class_path: cmmvae.modules.CMMVAE
    init_args:
      vae:
        class_path: cmmvae.modules.Autoencoder
        init_args:
          # latent_dim: 40
          encoder_config:
            class_path: cmmvae.modules.base.FCBlockConfig
            init_args:
              layers: [ 128, 64 ]
              dropout_rate: 0.0
              use_batch_norm: False
              use_layer_norm: True
              activation_fn: torch.nn.ReLU
              return_hidden: 
              - False
          decoder_config:
            class_path: cmmvae.modules.base.FCBlockConfig
            init_args:
              layers: [ 64, 128 ]
              dropout_rate: 0.0
              use_batch_norm: False
              use_layer_norm: True
              activation_fn: torch.nn.ReLU
      experts:
        class_path: cmmvae.modules.base.Experts
        init_args:
          experts:
          - class_path: cmmvae.modules.base.Expert
            init_args:
              id: human
              encoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [ 60530, 512, 128 ]
                  dropout_rate: [ 0.1, 0.0]
                  use_batch_norm: False
                  use_layer_norm: True
                  activation_fn: torch.nn.ReLU
              decoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [ 128, 512,  60530 ]
                  dropout_rate: 0.0
                  use_batch_norm: False
                  use_layer_norm: True
                  activation_fn: torch.nn.ReLU
          - class_path: cmmvae.modules.base.Expert
            init_args:
              id: mouse
              encoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [ 52437, 512, 128 ]
                  dropout_rate: [ 0.1, 0.0]
                  use_batch_norm: False
                  use_layer_norm: True
                  activation_fn: torch.nn.ReLU
              decoder_config:
                class_path: cmmvae.modules.base.FCBlockConfig
                init_args:
                  layers: [ 128, 512, 52437 ]
                  dropout_rate: 0.0
                  use_batch_norm: False
                  use_layer_norm: True
                  activation_fn: torch.nn.ReLU
      adversarial_groups:
        - class_path: cmmvae.modules.base.AdversarialsGroup
          init_args:
            conditional: human
            adversarials:
            - class_path: cmmvae.modules.base.FCBlockConfig
              init_args:
                layers: [ 60530, 128, 1 ]
                dropout_rate: 0.0
                use_batch_norm: False
                use_layer_norm: 
                - True
                - False
                activation_fn: 
                - torch.nn.ReLU
                - torch.nn.Sigmoid
        - class_path: cmmvae.modules.base.AdversarialsGroup
          init_args:
            conditional: mouse
            adversarials:
            - class_path: cmmvae.modules.base.FCBlockConfig
              init_args:
                layers: [ 52437, 128, 1 ]
                dropout_rate: 0.0
                use_batch_norm: False
                use_layer_norm: 
                - True
                - False
                activation_fn: 
                - torch.nn.ReLU
                - torch.nn.Sigmoid
